android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx1280m -XX:MaxMetaspaceSize=384m -XX:+HeapDumpOnOutOfMemoryError -XX:+UseG1GC -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=false
org.gradle.daemon=false
org.gradle.workers.max=1
org.gradle.java.installations.paths=/home/z/my-project/jdk/jdk-17.0.20+8
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.from.digests=false
kapt.use.k2=false
kapt.incremental.apt=false
kapt.include.compile.classpath=false
kotlin.compiler.execution.strategy=in-process
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
